# Generated by Django 5.2 on 2025-05-02 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User GreenGrow'},
        ),
        migrations.AlterField(
            model_name='sensor',
            name='greenhouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='dashboard.greenhouse'),
        ),
    ]
