# Generated by Django 5.2 on 2025-05-09 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_user_options_alter_sensor_greenhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actuator_type', models.CharField(choices=[('watering_valve', 'Watering Valve'), ('ventilation_fan', 'Ventilation Fan'), ('heating_element', 'Heating Element'), ('cooling_unit', 'Cooling Unit'), ('light', 'Light')], max_length=50)),
                ('name', models.CharField(help_text='Human-readable name for the actuator', max_length=100)),
                ('pin_number', models.CharField(blank=True, help_text='Physical pin or identifier if applicable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('greenhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='dashboard.greenhouse')),
            ],
        ),
        migrations.CreateModel(
            name='ActuatorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_value', models.CharField(help_text="The state or command value (e.g., 'on', 'off', '50%', 'open')", max_length=255)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='dashboard.actuator')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
